/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analysis/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_analysis_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Sensitivity */
        post: operations["run_sensitivity_analysis_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_deals__deal_id__get"];
        /** Update Deal */
        put: operations["update_deal_deals__deal_id__put"];
        post?: never;
        /** Delete Deal */
        delete: operations["delete_deal_deals__deal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            metrics: components["schemas"]["Metrics"];
            /** Years */
            years: components["schemas"]["YearRow"][];
            exit: components["schemas"]["Exit"];
            /**
             * Levered Cash Flows
             * @description Year 0..N, investor perspective
             */
            levered_cash_flows: number[];
            /**
             * Unlevered Cash Flows
             * @description Year 0..N, all-cash perspective
             */
            unlevered_cash_flows: number[];
        };
        /**
         * Deal
         * @description Everything needed to underwrite one income property over a hold period.
         */
        Deal: {
            /** Purchase Price */
            purchase_price: number;
            /**
             * Closing Costs Pct
             * @default 0.03
             */
            closing_costs_pct: number;
            /**
             * Rehab Cost
             * @default 0
             */
            rehab_cost: number;
            /**
             * After Repair Value
             * @description Value after rehab; defaults to the purchase price
             */
            after_repair_value?: number | null;
            /**
             * Monthly Rent
             * @description Gross scheduled rent for all units
             */
            monthly_rent: number;
            /**
             * Other Income Monthly
             * @default 0
             */
            other_income_monthly: number;
            /**
             * Vacancy Rate
             * @default 0.05
             */
            vacancy_rate: number;
            /**
             * Property Tax Annual
             * @default 0
             */
            property_tax_annual: number;
            /**
             * Insurance Annual
             * @default 0
             */
            insurance_annual: number;
            /**
             * Hoa Monthly
             * @default 0
             */
            hoa_monthly: number;
            /**
             * Utilities Monthly
             * @default 0
             */
            utilities_monthly: number;
            /**
             * Other Expenses Annual
             * @default 0
             */
            other_expenses_annual: number;
            /**
             * Management Pct
             * @default 0.08
             */
            management_pct: number;
            /**
             * Maintenance Pct
             * @default 0.05
             */
            maintenance_pct: number;
            /**
             * Capex Reserve Pct
             * @default 0.05
             */
            capex_reserve_pct: number;
            /**
             * Rent Growth
             * @default 0.03
             */
            rent_growth: number;
            /**
             * Expense Growth
             * @default 0.03
             */
            expense_growth: number;
            /**
             * Appreciation
             * @default 0.03
             */
            appreciation: number;
            /**
             * Hold Years
             * @default 10
             */
            hold_years: number;
            /**
             * Selling Costs Pct
             * @default 0.06
             */
            selling_costs_pct: number;
            /**
             * Exit Cap Rate
             * @description If set, exit value = next-year NOI / exit cap rate
             */
            exit_cap_rate?: number | null;
            financing?: components["schemas"]["Financing"] | null;
        };
        /** DealIn */
        DealIn: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Status
             * @default watching
             * @enum {string}
             */
            status: "watching" | "offer" | "owned" | "passed";
            inputs: components["schemas"]["Deal"];
        };
        /** DealOut */
        DealOut: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Status
             * @default watching
             * @enum {string}
             */
            status: "watching" | "offer" | "owned" | "passed";
            inputs: components["schemas"]["Deal"];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            metrics: components["schemas"]["Metrics"];
        };
        /** Exit */
        Exit: {
            /** Year */
            year: number;
            /** Sale Price */
            sale_price: number;
            /** Selling Costs */
            selling_costs: number;
            /** Loan Payoff */
            loan_payoff: number;
            /**
             * Net Proceeds
             * @description Cash to the investor after costs and payoff
             */
            net_proceeds: number;
        };
        /**
         * Financing
         * @description A fixed-rate, fully amortizing acquisition loan sized off the purchase price.
         */
        Financing: {
            /**
             * Down Payment Pct
             * @default 0.25
             */
            down_payment_pct: number;
            /**
             * Interest Rate
             * @default 0.07
             */
            interest_rate: number;
            /**
             * Amortization Years
             * @default 30
             */
            amortization_years: number;
            /**
             * Points Pct
             * @description Loan fees as a share of the loan
             * @default 0
             */
            points_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Metrics
         * @description Headline return metrics. Ratios are None when undefined (e.g. no debt).
         */
        Metrics: {
            /**
             * Total Capital
             * @description Price + closing costs + rehab
             */
            total_capital: number;
            /** Loan Amount */
            loan_amount: number;
            /**
             * Equity Invested
             * @description Cash in: down payment, closing, rehab, points
             */
            equity_invested: number;
            /** Noi Year1 */
            noi_year1: number;
            /** Cash Flow Year1 */
            cash_flow_year1: number;
            /**
             * Cap Rate
             * @description Year-one NOI / purchase price
             */
            cap_rate: number | null;
            /**
             * Roic
             * @description Year-one NOI / total capital (yield on cost)
             */
            roic: number | null;
            /**
             * Cash On Cash
             * @description Year-one cash flow / equity invested
             */
            cash_on_cash: number | null;
            /**
             * Dscr
             * @description Year-one NOI / debt service
             */
            dscr: number | null;
            /** Levered Irr */
            levered_irr: number | null;
            /** Unlevered Irr */
            unlevered_irr: number | null;
            /**
             * Equity Multiple
             * @description Total cash returned / equity invested
             */
            equity_multiple: number | null;
            /**
             * Total Profit
             * @description Total cash returned minus equity invested
             */
            total_profit: number;
            /** Gross Rent Multiplier */
            gross_rent_multiplier: number | null;
            /**
             * Rent To Price
             * @description Monthly rent / purchase price (the '1% rule')
             */
            rent_to_price: number;
            /**
             * Break Even Occupancy
             * @description Occupancy at which income covers expenses and debt service
             */
            break_even_occupancy: number | null;
        };
        /** SensitivityGrid */
        SensitivityGrid: {
            /** X Field */
            x_field: string;
            /** X Values */
            x_values: number[];
            /** Y Field */
            y_field: string;
            /** Y Values */
            y_values: number[];
            /** Metric */
            metric: string;
            /** Values */
            values: (number | null)[][];
        };
        /** SensitivityRequest */
        SensitivityRequest: {
            deal: components["schemas"]["Deal"];
            /** X Field */
            x_field: string;
            /** X Values */
            x_values: number[];
            /** Y Field */
            y_field: string;
            /** Y Values */
            y_values: number[];
            /**
             * Metric
             * @default levered_irr
             */
            metric: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * YearRow
         * @description One year of the pro forma. Balance and value are end-of-year figures.
         */
        YearRow: {
            /** Year */
            year: number;
            /** Gross Potential Rent */
            gross_potential_rent: number;
            /** Vacancy Loss */
            vacancy_loss: number;
            /** Other Income */
            other_income: number;
            /** Effective Gross Income */
            effective_gross_income: number;
            /** Fixed Expenses */
            fixed_expenses: number;
            /** Variable Expenses */
            variable_expenses: number;
            /** Operating Expenses */
            operating_expenses: number;
            /** Noi */
            noi: number;
            /** Debt Service */
            debt_service: number;
            /** Cash Flow */
            cash_flow: number;
            /** Loan Balance */
            loan_balance: number;
            /** Property Value */
            property_value: number;
            /** Equity */
            equity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    template_analysis_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
        };
    };
    run_analysis_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deal"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_sensitivity_analysis_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityGrid"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deals_deals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"][];
                };
            };
        };
    };
    create_deal_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_deals__deal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deal_deals__deal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
