/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analysis/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Template */
        get: operations["template_analysis_template_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analysis/sensitivity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Sensitivity */
        post: operations["run_sensitivity_analysis_sensitivity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deals */
        get: operations["list_deals_deals_get"];
        put?: never;
        /** Create Deal */
        post: operations["create_deal_deals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deal */
        get: operations["get_deal_deals__deal_id__get"];
        /** Update Deal */
        put: operations["update_deal_deals__deal_id__put"];
        post?: never;
        /** Delete Deal */
        delete: operations["delete_deal_deals__deal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Markets
         * @description Every geography with rent or home-value data, largest first (country on top).
         */
        get: operations["list_markets_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicators
         * @description National series for the ticker tape and macro panel.
         */
        get: operations["indicators_markets_indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_markets_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/{geography_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Detail */
        get: operations["market_detail_markets__geography_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categories */
        get: operations["categories_portfolio_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Property */
        post: operations["create_property_portfolio_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/from-deal/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create From Deal
         * @description Turn a watchlist deal into an owned property, keeping it linked for comparisons.
         */
        post: operations["create_from_deal_portfolio_properties_from_deal__deal_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Property */
        get: operations["get_property_portfolio_properties__property_id__get"];
        /** Update Property */
        put: operations["update_property_portfolio_properties__property_id__put"];
        post?: never;
        /** Delete Property */
        delete: operations["delete_property_portfolio_properties__property_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Lease */
        post: operations["add_lease_portfolio_properties__property_id__leases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/leases/{lease_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Lease */
        put: operations["update_lease_portfolio_leases__lease_id__put"];
        post?: never;
        /** Delete Lease */
        delete: operations["delete_lease_portfolio_leases__lease_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_portfolio_properties__property_id__transactions_get"];
        put?: never;
        /** Add Transaction */
        post: operations["add_transaction_portfolio_properties__property_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}/transactions/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Transactions
         * @description Import a bank/property-manager CSV. Lines seen in earlier imports are skipped.
         */
        post: operations["import_transactions_portfolio_properties__property_id__transactions_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}/transactions/rent-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Rent Range
         * @description Record rent for many months at once, one ledger line per month.
         *
         *     Stops at the current month: future rent is a projection, not a transaction.
         */
        post: operations["record_rent_range_portfolio_properties__property_id__transactions_rent_range_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/properties/{property_id}/transactions/bulk-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Delete Transactions
         * @description Delete several ledger lines of one property (e.g. undoing a rent range).
         */
        post: operations["bulk_delete_transactions_portfolio_properties__property_id__transactions_bulk_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Transaction */
        delete: operations["delete_transaction_portfolio_transactions__transaction_id__delete"];
        options?: never;
        head?: never;
        /** Update Transaction */
        patch: operations["update_transaction_portfolio_transactions__transaction_id__patch"];
        trace?: never;
    };
    "/portfolio/properties/{property_id}/valuations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Valuation */
        post: operations["add_valuation_portfolio_properties__property_id__valuations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/valuations/{valuation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Valuation */
        delete: operations["delete_valuation_portfolio_valuations__valuation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buy-boxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Boxes */
        get: operations["list_boxes_buy_boxes_get"];
        put?: never;
        /** Create Box */
        post: operations["create_box_buy_boxes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buy-boxes/{box_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Box */
        put: operations["update_box_buy_boxes__box_id__put"];
        post?: never;
        /** Delete Box */
        delete: operations["delete_box_buy_boxes__box_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buy-boxes/{box_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_buy_boxes__box_id__recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buy-boxes/{box_id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Seen */
        post: operations["mark_seen_buy_boxes__box_id__seen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/screener/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts
         * @description New BUY-or-better matches per buy box since each was last viewed.
         */
        get: operations["alerts_screener_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing Sources */
        get: operations["listing_sources_listings_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Listings
         * @description Import a listings CSV (e.g. a Redfin "Download All" export of your search).
         */
        post: operations["import_listings_listings_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing Detail */
        get: operations["listing_detail_listings__listing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Listing
         * @description Override the rent estimate or the unit count. Send rent_override=null to clear.
         */
        patch: operations["patch_listing_listings__listing_id__patch"];
        trace?: never;
    };
    "/listings/{listing_id}/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add To Watchlist
         * @description Save the listing, underwritten with the buy box's assumptions, as a watchlist deal.
         */
        post: operations["add_to_watchlist_listings__listing_id__watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alerts */
        Alerts: {
            /** Total New */
            total_new: number;
            /** By Box */
            by_box: {
                [key: string]: number;
            };
        };
        /** Analysis */
        Analysis: {
            metrics: components["schemas"]["Metrics"];
            /** Years */
            years: components["schemas"]["YearRow"][];
            exit: components["schemas"]["Exit"];
            /**
             * Levered Cash Flows
             * @description Year 0..N, investor perspective
             */
            levered_cash_flows: number[];
            /**
             * Unlevered Cash Flows
             * @description Year 0..N, all-cash perspective
             */
            unlevered_cash_flows: number[];
        };
        /** Assumptions */
        Assumptions: {
            /**
             * Down Payment Pct
             * @default 0.25
             */
            down_payment_pct: number;
            /**
             * Interest Rate
             * @description None = current 30Y average plus rate_spread
             */
            interest_rate?: number | null;
            /**
             * Rate Spread
             * @description Investor-loan premium
             * @default 0.0075
             */
            rate_spread: number;
            /**
             * Amortization Years
             * @default 30
             */
            amortization_years: number;
            /**
             * Closing Costs Pct
             * @default 0.03
             */
            closing_costs_pct: number;
            /**
             * Rehab Pct
             * @description Make-ready budget, % of price
             * @default 0.02
             */
            rehab_pct: number;
            /**
             * Vacancy Rate
             * @default 0.06
             */
            vacancy_rate: number;
            /**
             * Management Pct
             * @default 0.08
             */
            management_pct: number;
            /**
             * Maintenance Pct
             * @default 0.06
             */
            maintenance_pct: number;
            /**
             * Capex Reserve Pct
             * @default 0.06
             */
            capex_reserve_pct: number;
            /**
             * Property Tax Rate
             * @description Annual, % of price
             * @default 0.011
             */
            property_tax_rate: number;
            /**
             * Insurance Rate
             * @description Annual, % of price
             * @default 0.005
             */
            insurance_rate: number;
            /**
             * Growth
             * @default market
             * @enum {string}
             */
            growth: "market" | "fixed";
            /**
             * Rent Growth
             * @default 0.025
             */
            rent_growth: number;
            /**
             * Appreciation
             * @default 0.03
             */
            appreciation: number;
            /**
             * Growth Floor
             * @default 0
             */
            growth_floor: number;
            /**
             * Growth Cap
             * @default 0.03
             */
            growth_cap: number;
            /**
             * Hold Years
             * @default 7
             */
            hold_years: number;
            /**
             * Selling Costs Pct
             * @default 0.06
             */
            selling_costs_pct: number;
        };
        /** BulkDeleteIn */
        BulkDeleteIn: {
            /** Ids */
            ids: number[];
        };
        /** BuyBoxIn */
        BuyBoxIn: {
            /** Name */
            name: string;
            criteria?: components["schemas"]["Criteria"];
            assumptions?: components["schemas"]["Assumptions"];
        };
        /** BuyBoxOut */
        BuyBoxOut: {
            /** Name */
            name: string;
            criteria?: components["schemas"]["Criteria"];
            assumptions?: components["schemas"]["Assumptions"];
            /** Id */
            id: number;
            /** Last Viewed At */
            last_viewed_at: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Group */
            group: string;
        };
        /** Check */
        Check: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
            /** Target */
            target: number;
            /** Passed */
            passed: boolean;
        };
        /** Criteria */
        Criteria: {
            /**
             * Market Ids
             * @description Empty = any market
             */
            market_ids?: number[];
            /** Property Types */
            property_types?: ("single_family" | "multi_2_4" | "condo" | "multifamily" | "commercial" | "land")[];
            /** Min Price */
            min_price?: number | null;
            /**
             * Max Price
             * @default 500000
             */
            max_price: number | null;
            /** Min Beds */
            min_beds?: number | null;
            /** Max Days On Market */
            max_days_on_market?: number | null;
            /** Min Year Built */
            min_year_built?: number | null;
            /**
             * Min Levered Irr
             * @default 0.12
             */
            min_levered_irr: number;
            /**
             * Min Cash On Cash
             * @default 0.06
             */
            min_cash_on_cash: number;
            /**
             * Min Dscr
             * @default 1.2
             */
            min_dscr: number;
            /** Min Cap Rate */
            min_cap_rate?: number | null;
        };
        /**
         * Deal
         * @description Everything needed to underwrite one income property over a hold period.
         */
        Deal: {
            /** Purchase Price */
            purchase_price: number;
            /**
             * Closing Costs Pct
             * @default 0.03
             */
            closing_costs_pct: number;
            /**
             * Rehab Cost
             * @default 0
             */
            rehab_cost: number;
            /**
             * After Repair Value
             * @description Value after rehab; defaults to the purchase price
             */
            after_repair_value?: number | null;
            /**
             * Monthly Rent
             * @description Gross scheduled rent for all units
             */
            monthly_rent: number;
            /**
             * Other Income Monthly
             * @default 0
             */
            other_income_monthly: number;
            /**
             * Vacancy Rate
             * @default 0.05
             */
            vacancy_rate: number;
            /**
             * Property Tax Annual
             * @default 0
             */
            property_tax_annual: number;
            /**
             * Insurance Annual
             * @default 0
             */
            insurance_annual: number;
            /**
             * Hoa Monthly
             * @default 0
             */
            hoa_monthly: number;
            /**
             * Utilities Monthly
             * @default 0
             */
            utilities_monthly: number;
            /**
             * Other Expenses Annual
             * @default 0
             */
            other_expenses_annual: number;
            /**
             * Management Pct
             * @default 0.08
             */
            management_pct: number;
            /**
             * Maintenance Pct
             * @default 0.05
             */
            maintenance_pct: number;
            /**
             * Capex Reserve Pct
             * @default 0.05
             */
            capex_reserve_pct: number;
            /**
             * Rent Growth
             * @default 0.03
             */
            rent_growth: number;
            /**
             * Expense Growth
             * @default 0.03
             */
            expense_growth: number;
            /**
             * Appreciation
             * @default 0.03
             */
            appreciation: number;
            /**
             * Hold Years
             * @default 10
             */
            hold_years: number;
            /**
             * Selling Costs Pct
             * @default 0.06
             */
            selling_costs_pct: number;
            /**
             * Exit Cap Rate
             * @description If set, exit value = next-year NOI / exit cap rate
             */
            exit_cap_rate?: number | null;
            financing?: components["schemas"]["Financing"] | null;
        };
        /** DealIn */
        DealIn: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Status
             * @default watching
             * @enum {string}
             */
            status: "watching" | "offer" | "owned" | "passed";
            inputs: components["schemas"]["Deal"];
        };
        /** DealOut */
        DealOut: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Status
             * @default watching
             * @enum {string}
             */
            status: "watching" | "offer" | "owned" | "passed";
            inputs: components["schemas"]["Deal"];
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            metrics: components["schemas"]["Metrics"];
        };
        /** Evaluation */
        Evaluation: {
            /** Score */
            score: number;
            /**
             * Signal
             * @enum {string}
             */
            signal: "STRONG BUY" | "BUY" | "WATCH" | "PASS";
            /** Components */
            components: {
                [key: string]: number;
            };
            /** Checks */
            checks: components["schemas"]["Check"][];
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            metrics: components["schemas"]["Metrics"];
            /** Stress Irr */
            stress_irr: number | null;
            deal: components["schemas"]["Deal"];
        };
        /** Exit */
        Exit: {
            /** Year */
            year: number;
            /** Sale Price */
            sale_price: number;
            /** Selling Costs */
            selling_costs: number;
            /** Loan Payoff */
            loan_payoff: number;
            /**
             * Net Proceeds
             * @description Cash to the investor after costs and payoff
             */
            net_proceeds: number;
        };
        /**
         * Financing
         * @description A fixed-rate, fully amortizing acquisition loan sized off the purchase price.
         */
        Financing: {
            /**
             * Down Payment Pct
             * @default 0.25
             */
            down_payment_pct: number;
            /**
             * Interest Rate
             * @default 0.07
             */
            interest_rate: number;
            /**
             * Amortization Years
             * @default 30
             */
            amortization_years: number;
            /**
             * Points Pct
             * @description Loan fees as a share of the loan
             * @default 0
             */
            points_pct: number;
        };
        /** GeographyOut */
        GeographyOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** State */
            state: string | null;
            /** Size Rank */
            size_rank: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Holding */
        Holding: {
            property: components["schemas"]["PropertyOut"];
            performance: components["schemas"]["Performance"];
        };
        /** ImportIn */
        ImportIn: {
            /** Csv */
            csv: string;
        };
        /** ImportOut */
        ImportOut: {
            /** Imported */
            imported: number;
            /** Skipped Duplicates */
            skipped_duplicates: number;
            /** Guessed */
            guessed: number;
            /** Uncategorized */
            uncategorized: number;
        };
        /** Indicator */
        Indicator: {
            /** Metric */
            metric: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Frequency */
            frequency: string;
            /** Source */
            source: string;
            /** Demo */
            demo: boolean;
            stats: components["schemas"]["SeriesStats"] | null;
            /** Spark */
            spark: components["schemas"]["Point"][];
        };
        /** LeaseIn */
        LeaseIn: {
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Tenant */
            tenant?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Monthly Rent */
            monthly_rent: number | string;
            /**
             * Deposit
             * @default 0
             */
            deposit: number | string;
        };
        /** LeaseOut */
        LeaseOut: {
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Tenant */
            tenant?: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Monthly Rent */
            monthly_rent: number;
            /**
             * Deposit
             * @default 0
             */
            deposit: number;
            /** Id */
            id: number;
            /** Active */
            active: boolean;
        };
        /** ListingDetail */
        ListingDetail: {
            listing: components["schemas"]["ListingOut"];
            /** Events */
            events: components["schemas"]["ListingEventOut"][];
            rent: components["schemas"]["RentEstimate"] | null;
            evaluation: components["schemas"]["Evaluation"] | null;
            /** Filtered Because */
            filtered_because: string[];
        };
        /** ListingEventOut */
        ListingEventOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Event */
            event: string;
            /** Price */
            price: number | null;
        };
        /** ListingImportIn */
        ListingImportIn: {
            /** Csv */
            csv: string;
        };
        /** ListingImportOut */
        ListingImportOut: {
            /** Source */
            source: string;
            /** New */
            new: number;
            /** Updated */
            updated: number;
            /** Price Changes */
            price_changes: number;
        };
        /** ListingOut */
        ListingOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Address */
            address: string;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Zip */
            zip: string | null;
            /** Market Id */
            market_id: number | null;
            /** Market Name */
            market_name: string | null;
            /** Property Type */
            property_type: string;
            /** Units */
            units: number;
            /** Units Inferred */
            units_inferred: boolean;
            /** Beds */
            beds: number | null;
            /** Baths */
            baths: number | null;
            /** Sqft */
            sqft: number | null;
            /** Year Built */
            year_built: number | null;
            /** Hoa Monthly */
            hoa_monthly: number | null;
            /** Price */
            price: number;
            /** Status */
            status: string;
            /** Days On Market */
            days_on_market: number | null;
            /** Url */
            url: string | null;
            /** Stated Rent */
            stated_rent: number | null;
            /** Rent Override */
            rent_override: number | null;
            /** Price Change */
            price_change: number | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
        };
        /** ListingPatch */
        ListingPatch: {
            /** Rent Override */
            rent_override?: number | null;
            /** Units */
            units?: number | null;
        };
        /** LoanIn */
        LoanIn: {
            /** Lender */
            lender?: string | null;
            /** Original Amount */
            original_amount: number | string;
            /** Interest Rate */
            interest_rate: number;
            /** Amortization Years */
            amortization_years: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** LoanOut */
        LoanOut: {
            /** Lender */
            lender?: string | null;
            /** Original Amount */
            original_amount: number;
            /** Interest Rate */
            interest_rate: number;
            /** Amortization Years */
            amortization_years: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Monthly Payment */
            monthly_payment: number;
        };
        /** MarketDetail */
        MarketDetail: {
            summary: components["schemas"]["MarketSummary"];
            /** Series */
            series: components["schemas"]["SeriesOut"][];
        };
        /** MarketSummary */
        MarketSummary: {
            geography: components["schemas"]["GeographyOut"];
            rent: components["schemas"]["SeriesStats"] | null;
            home_value: components["schemas"]["SeriesStats"] | null;
            /** Gross Yield */
            gross_yield: number | null;
            /** Rent Spark */
            rent_spark: number[];
            /** Sources */
            sources: string[];
            /** Demo */
            demo: boolean;
        };
        /**
         * Metrics
         * @description Headline return metrics. Ratios are None when undefined (e.g. no debt).
         */
        Metrics: {
            /**
             * Total Capital
             * @description Price + closing costs + rehab
             */
            total_capital: number;
            /** Loan Amount */
            loan_amount: number;
            /**
             * Equity Invested
             * @description Cash in: down payment, closing, rehab, points
             */
            equity_invested: number;
            /** Noi Year1 */
            noi_year1: number;
            /** Cash Flow Year1 */
            cash_flow_year1: number;
            /**
             * Cap Rate
             * @description Year-one NOI / purchase price
             */
            cap_rate: number | null;
            /**
             * Roic
             * @description Year-one NOI / total capital (yield on cost)
             */
            roic: number | null;
            /**
             * Cash On Cash
             * @description Year-one cash flow / equity invested
             */
            cash_on_cash: number | null;
            /**
             * Dscr
             * @description Year-one NOI / debt service
             */
            dscr: number | null;
            /** Levered Irr */
            levered_irr: number | null;
            /** Unlevered Irr */
            unlevered_irr: number | null;
            /**
             * Equity Multiple
             * @description Total cash returned / equity invested
             */
            equity_multiple: number | null;
            /**
             * Total Profit
             * @description Total cash returned minus equity invested
             */
            total_profit: number;
            /** Gross Rent Multiplier */
            gross_rent_multiplier: number | null;
            /**
             * Rent To Price
             * @description Monthly rent / purchase price (the '1% rule')
             */
            rent_to_price: number;
            /**
             * Break Even Occupancy
             * @description Occupancy at which income covers expenses and debt service
             */
            break_even_occupancy: number | null;
        };
        /** MonthRow */
        MonthRow: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Income */
            income: number;
            /** Operating Expenses */
            operating_expenses: number;
            /** Noi */
            noi: number;
            /** Capex */
            capex: number;
            /** Debt Service */
            debt_service: number;
            /** Cash Flow */
            cash_flow: number;
            /** Value */
            value: number;
            /** Loan Balance */
            loan_balance: number;
            /** Equity */
            equity: number;
        };
        /** Performance */
        Performance: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Sold */
            sold: boolean;
            /** Months Held */
            months_held: number;
            /** Cost Basis */
            cost_basis: number;
            /** Loan Amount */
            loan_amount: number;
            /** Equity Invested */
            equity_invested: number;
            /** Value */
            value: number;
            /** Value Source */
            value_source: string;
            /** Loan Balance */
            loan_balance: number;
            /** Equity */
            equity: number;
            /** Ltv */
            ltv: number | null;
            /** Gain */
            gain: number;
            /** Gain Pct */
            gain_pct: number | null;
            t12: components["schemas"]["PeriodTotals"];
            /** Noi Annualized */
            noi_annualized: number | null;
            /** Cash Flow Annualized */
            cash_flow_annualized: number | null;
            /** Cap Rate On Cost */
            cap_rate_on_cost: number | null;
            /** Cap Rate On Value */
            cap_rate_on_value: number | null;
            /** Cash On Cash */
            cash_on_cash: number | null;
            /** Irr */
            irr: number | null;
            /** Equity Multiple */
            equity_multiple: number | null;
            /** Total Return */
            total_return: number;
            /** Distributions */
            distributions: number;
            /** Units */
            units: number;
            /** Occupied Units */
            occupied_units: number;
            /** Occupancy */
            occupancy: number | null;
            /** Scheduled Rent */
            scheduled_rent: number;
            /** Debt Service Imputed */
            debt_service_imputed: boolean;
            /** Uncategorized Count */
            uncategorized_count: number;
        };
        /** PeriodTotals */
        PeriodTotals: {
            /** Months */
            months: number;
            /** Income */
            income: number;
            /** Operating Expenses */
            operating_expenses: number;
            /** Noi */
            noi: number;
            /** Capex */
            capex: number;
            /** Debt Service */
            debt_service: number;
            /** Uncategorized */
            uncategorized: number;
            /** Cash Flow */
            cash_flow: number;
        };
        /** Point */
        Point: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
        };
        /** PortfolioMonth */
        PortfolioMonth: {
            /**
             * Month
             * Format: date
             */
            month: string;
            /** Value */
            value: number;
            /** Loan Balance */
            loan_balance: number;
            /** Equity */
            equity: number;
            /** Cash Flow */
            cash_flow: number;
            /** Noi */
            noi: number;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            totals: components["schemas"]["Totals"];
            /** Holdings */
            holdings: components["schemas"]["Holding"][];
            /** Months */
            months: components["schemas"]["PortfolioMonth"][];
            /** By Market */
            by_market: components["schemas"]["Slice"][];
            /** By Type */
            by_type: components["schemas"]["Slice"][];
        };
        /** ProFormaComparison */
        ProFormaComparison: {
            /** Deal Id */
            deal_id: number;
            /** Deal Name */
            deal_name: string;
            /** Projection Year */
            projection_year: number;
            /** Rows */
            rows: components["schemas"]["VarianceRow"][];
        };
        /** PropertyDetail */
        PropertyDetail: {
            property: components["schemas"]["PropertyOut"];
            performance: components["schemas"]["Performance"];
            /** Monthly */
            monthly: components["schemas"]["MonthRow"][];
            /** Leases */
            leases: components["schemas"]["LeaseOut"][];
            /** Valuations */
            valuations: components["schemas"]["ValuationOut"][];
            pro_forma: components["schemas"]["ProFormaComparison"] | null;
        };
        /** PropertyIn */
        PropertyIn: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Property Type
             * @default single_family
             * @enum {string}
             */
            property_type: "single_family" | "multi_2_4" | "condo" | "multifamily" | "commercial" | "land";
            /**
             * Units
             * @default 1
             */
            units: number;
            /** Market Id */
            market_id?: number | null;
            /** Deal Id */
            deal_id?: number | null;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            /** Purchase Price */
            purchase_price: number | string;
            /**
             * Closing Costs
             * @default 0
             */
            closing_costs: number | string;
            /**
             * Rehab Cost
             * @default 0
             */
            rehab_cost: number | string;
            /** Sale Date */
            sale_date?: string | null;
            /** Sale Price */
            sale_price?: (number | string) | null;
            /** Selling Costs */
            selling_costs?: (number | string) | null;
            /** Notes */
            notes?: string | null;
            loan?: components["schemas"]["LoanIn"] | null;
        };
        /** PropertyOut */
        PropertyOut: {
            /** Name */
            name: string;
            /** Address */
            address?: string | null;
            /**
             * Property Type
             * @default single_family
             * @enum {string}
             */
            property_type: "single_family" | "multi_2_4" | "condo" | "multifamily" | "commercial" | "land";
            /**
             * Units
             * @default 1
             */
            units: number;
            /** Market Id */
            market_id?: number | null;
            /** Deal Id */
            deal_id?: number | null;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            /** Purchase Price */
            purchase_price: number;
            /**
             * Closing Costs
             * @default 0
             */
            closing_costs: number;
            /**
             * Rehab Cost
             * @default 0
             */
            rehab_cost: number;
            /** Sale Date */
            sale_date?: string | null;
            /** Sale Price */
            sale_price?: number | null;
            /** Selling Costs */
            selling_costs?: number | null;
            /** Notes */
            notes?: string | null;
            loan?: components["schemas"]["LoanOut"] | null;
            /** Id */
            id: number;
            /** Market Name */
            market_name: string | null;
        };
        /** Reason */
        Reason: {
            /** Text */
            text: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "up" | "down" | "flat";
        };
        /** RecommendationOut */
        RecommendationOut: {
            listing: components["schemas"]["ListingOut"];
            rent: components["schemas"]["RentEstimate"];
            evaluation: components["schemas"]["Evaluation"];
            /** Is New */
            is_new: boolean;
        };
        /** RecommendationsOut */
        RecommendationsOut: {
            buy_box: components["schemas"]["BuyBoxOut"];
            summary: components["schemas"]["Summary"];
            /** Rows */
            rows: components["schemas"]["RecommendationOut"][];
        };
        /** RentEstimate */
        RentEstimate: {
            /** Monthly */
            monthly: number;
            /**
             * Source
             * @enum {string}
             */
            source: "override" | "stated" | "model";
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Basis */
            basis: string;
        };
        /** RentLineOut */
        RentLineOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Amount */
            amount: number;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "already_recorded" | "month_has_rent";
        };
        /**
         * RentRangeIn
         * @description Record rent for a run of months in one step: a flat amount or a lease's rent.
         */
        RentRangeIn: {
            /**
             * Start Month
             * @example 2024-01
             */
            start_month: string;
            /**
             * End Month
             * @example 2026-09
             */
            end_month: string;
            /**
             * Monthly Amount
             * @description Defaults to the lease's rent
             */
            monthly_amount?: (number | string) | null;
            /** Lease Id */
            lease_id?: number | null;
            /**
             * Day Of Month
             * @description Clamped to the month's length
             * @default 1
             */
            day_of_month: number;
            /**
             * Annual Increase
             * @description Step-up every 12 months
             * @default 0
             */
            annual_increase: number;
            /**
             * Category
             * @default rent
             * @enum {string}
             */
            category: "rent" | "other_income";
            /** Description */
            description?: string | null;
            /**
             * Skip Months With Rent
             * @description Skip months that already have a rent entry from any source
             * @default true
             */
            skip_months_with_rent: boolean;
            /**
             * Dry Run
             * @description Preview without saving
             * @default false
             */
            dry_run: boolean;
        };
        /** RentRangeOut */
        RentRangeOut: {
            /** Months */
            months: number;
            /** Created */
            created: number;
            /** Skipped Already Recorded */
            skipped_already_recorded: number;
            /** Skipped Month Has Rent */
            skipped_month_has_rent: number;
            /** Total */
            total: number;
            /** Description */
            description: string;
            /** Lines */
            lines: components["schemas"]["RentLineOut"][];
            /** Created Ids */
            created_ids: number[];
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: number;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Series Count */
            series_count: number;
            /** Observation Count */
            observation_count: number;
            /** Error */
            error: string | null;
        };
        /** SensitivityGrid */
        SensitivityGrid: {
            /** X Field */
            x_field: string;
            /** X Values */
            x_values: number[];
            /** Y Field */
            y_field: string;
            /** Y Values */
            y_values: number[];
            /** Metric */
            metric: string;
            /** Values */
            values: (number | null)[][];
        };
        /** SensitivityRequest */
        SensitivityRequest: {
            deal: components["schemas"]["Deal"];
            /** X Field */
            x_field: string;
            /** X Values */
            x_values: number[];
            /** Y Field */
            y_field: string;
            /** Y Values */
            y_values: number[];
            /**
             * Metric
             * @default levered_irr
             */
            metric: string;
        };
        /** SeriesOut */
        SeriesOut: {
            /** Metric */
            metric: string;
            /** Unit */
            unit: string;
            /** Frequency */
            frequency: string;
            /** Source */
            source: string;
            /** Attribution */
            attribution: string;
            stats: components["schemas"]["SeriesStats"] | null;
            /** Points */
            points: components["schemas"]["Point"][];
        };
        /** SeriesStats */
        SeriesStats: {
            /** Latest */
            latest: number;
            /**
             * Latest Date
             * Format: date
             */
            latest_date: string;
            /** Previous */
            previous?: number | null;
            /** Change */
            change?: number | null;
            /** Change Pct */
            change_pct?: number | null;
            /** Yoy */
            yoy?: number | null;
            /** Yoy Abs */
            yoy_abs?: number | null;
            /** Cagr 3Y */
            cagr_3y?: number | null;
            /** Cagr 5Y */
            cagr_5y?: number | null;
        };
        /** Slice */
        Slice: {
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Share */
            share: number;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Rentcast Configured */
            rentcast_configured: boolean;
            /** Listing Areas */
            listing_areas: string[];
            /** Active Listings */
            active_listings: number;
            /** Runs */
            runs: {
                [key: string]: unknown;
            }[];
        };
        /** SourcesOut */
        SourcesOut: {
            /** Runs */
            runs: components["schemas"]["RunOut"][];
            /** Attributions */
            attributions: {
                [key: string]: string;
            };
        };
        /** Summary */
        Summary: {
            /** Scanned */
            scanned: number;
            /** Filtered Out */
            filtered_out: number;
            /** Evaluated */
            evaluated: number;
            /** Strong Buy */
            strong_buy: number;
            /** Buy */
            buy: number;
            /** Watch */
            watch: number;
            /** New Matches */
            new_matches: number;
            /** Interest Rate */
            interest_rate: number;
            /** Demo */
            demo: boolean;
        };
        /** Totals */
        Totals: {
            /** Properties */
            properties: number;
            /** Units */
            units: number;
            /** Occupied Units */
            occupied_units: number;
            /** Occupancy */
            occupancy: number | null;
            /** Cost Basis */
            cost_basis: number;
            /** Value */
            value: number;
            /** Loan Balance */
            loan_balance: number;
            /** Equity */
            equity: number;
            /** Ltv */
            ltv: number | null;
            /** Gain */
            gain: number;
            /** Equity Invested */
            equity_invested: number;
            /** Noi Annualized */
            noi_annualized: number;
            /** Cash Flow Annualized */
            cash_flow_annualized: number;
            /** Scheduled Rent */
            scheduled_rent: number;
            /** Cap Rate On Value */
            cap_rate_on_value: number | null;
            /** Cash On Cash */
            cash_on_cash: number | null;
            /** Irr */
            irr: number | null;
            /** Total Return */
            total_return: number;
            /** Distributions */
            distributions: number;
        };
        /** TransactionIn */
        TransactionIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Amount
             * @description Signed: positive money in, negative money out
             */
            amount: number | string;
            /**
             * Category
             * @enum {string}
             */
            category: "rent" | "other_income" | "property_tax" | "insurance" | "hoa" | "utilities" | "maintenance" | "management" | "other_expense" | "capex" | "debt_service" | "transfer" | "uncategorized";
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** TransactionOut */
        TransactionOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Amount
             * @description Signed: positive money in, negative money out
             */
            amount: number;
            /**
             * Category
             * @enum {string}
             */
            category: "rent" | "other_income" | "property_tax" | "insurance" | "hoa" | "utilities" | "maintenance" | "management" | "other_expense" | "capex" | "debt_service" | "transfer" | "uncategorized";
            /**
             * Description
             * @default
             */
            description: string;
            /** Id */
            id: number;
            /** Group */
            group: string;
            /** Imported */
            imported: boolean;
        };
        /** TransactionPatch */
        TransactionPatch: {
            /** Category */
            category?: ("rent" | "other_income" | "property_tax" | "insurance" | "hoa" | "utilities" | "maintenance" | "management" | "other_expense" | "capex" | "debt_service" | "transfer" | "uncategorized") | null;
            /** Description */
            description?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuationIn */
        ValuationIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number | string;
            /** Note */
            note?: string | null;
        };
        /** ValuationOut */
        ValuationOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
            /** Note */
            note?: string | null;
            /** Id */
            id: number;
        };
        /** VarianceRow */
        VarianceRow: {
            /** Label */
            label: string;
            /** Projected */
            projected: number;
            /** Actual */
            actual: number | null;
            /** Variance */
            variance: number | null;
            /** Variance Pct */
            variance_pct: number | null;
            /** Higher Is Better */
            higher_is_better: boolean;
        };
        /**
         * YearRow
         * @description One year of the pro forma. Balance and value are end-of-year figures.
         */
        YearRow: {
            /** Year */
            year: number;
            /** Gross Potential Rent */
            gross_potential_rent: number;
            /** Vacancy Loss */
            vacancy_loss: number;
            /** Other Income */
            other_income: number;
            /** Effective Gross Income */
            effective_gross_income: number;
            /** Fixed Expenses */
            fixed_expenses: number;
            /** Variable Expenses */
            variable_expenses: number;
            /** Operating Expenses */
            operating_expenses: number;
            /** Noi */
            noi: number;
            /** Debt Service */
            debt_service: number;
            /** Cash Flow */
            cash_flow: number;
            /** Loan Balance */
            loan_balance: number;
            /** Property Value */
            property_value: number;
            /** Equity */
            equity: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    template_analysis_template_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deal"];
                };
            };
        };
    };
    run_analysis_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deal"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_sensitivity_analysis_sensitivity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensitivityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensitivityGrid"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deals_deals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"][];
                };
            };
        };
    };
    create_deal_deals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deal_deals__deal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_deal_deals__deal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DealIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_deal_deals__deal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_markets_markets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketSummary"][];
                };
            };
        };
    };
    indicators_markets_indicators_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Indicator"][];
                };
            };
        };
    };
    sources_markets_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesOut"];
                };
            };
        };
    };
    market_detail_markets__geography_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                geography_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
        };
    };
    categories_portfolio_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_property_portfolio_properties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_from_deal_portfolio_properties_from_deal__deal_id__post: {
        parameters: {
            query: {
                purchase_date: string;
            };
            header?: never;
            path: {
                deal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_property_portfolio_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_property_portfolio_properties__property_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_property_portfolio_properties__property_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_lease_portfolio_properties__property_id__leases_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lease_portfolio_leases__lease_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeaseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lease_portfolio_leases__lease_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_portfolio_properties__property_id__transactions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_transaction_portfolio_properties__property_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_transactions_portfolio_properties__property_id__transactions_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_rent_range_portfolio_properties__property_id__transactions_rent_range_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RentRangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RentRangeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_delete_transactions_portfolio_properties__property_id__transactions_bulk_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDeleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_transaction_portfolio_transactions__transaction_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_transaction_portfolio_transactions__transaction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_valuation_portfolio_properties__property_id__valuations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValuationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValuationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_valuation_portfolio_valuations__valuation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                valuation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_boxes_buy_boxes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyBoxOut"][];
                };
            };
        };
    };
    create_box_buy_boxes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyBoxIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyBoxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_box_buy_boxes__box_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                box_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyBoxIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyBoxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_box_buy_boxes__box_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                box_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_buy_boxes__box_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                box_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_seen_buy_boxes__box_id__seen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                box_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alerts_screener_alerts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alerts"];
                };
            };
        };
    };
    listing_sources_listings_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceStatus"];
                };
            };
        };
    };
    import_listings_listings_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingImportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingImportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_detail_listings__listing_id__get: {
        parameters: {
            query: {
                buy_box_id: number;
            };
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_listing_listings__listing_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_listings__listing_id__watchlist_post: {
        parameters: {
            query: {
                buy_box_id: number;
            };
            header?: never;
            path: {
                listing_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
